# Generated by Django 4.0.1 on 2024-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Damas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gentra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Nexia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Spark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
    ]
