# Generated by Django 4.0.1 on 2024-01-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equinox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lacetti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Malibu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Malibu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Matiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Monza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Onix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('more', models.CharField(max_length=120)),
                ('images', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=64)),
                ('avto', models.CharField(max_length=15)),
            ],
        ),
    ]
