# Generated by Django 4.0.1 on 2024-01-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(max_length=12)),
                ('stage', models.CharField(max_length=12)),
                ('index_Spark', models.PositiveIntegerField(max_length=3)),
                ('index_Labo', models.PositiveIntegerField(max_length=3)),
                ('index_Nexia', models.PositiveIntegerField(max_length=3)),
                ('index_Cobalt', models.PositiveIntegerField(max_length=3)),
                ('index_Gentra', models.PositiveIntegerField(max_length=3)),
                ('index_Lacetti', models.PositiveIntegerField(max_length=3)),
                ('index_Malibu', models.PositiveIntegerField(max_length=3)),
                ('index_Malibu2', models.PositiveIntegerField(max_length=3)),
                ('index_Equinox', models.PositiveIntegerField(max_length=3)),
                ('index_Monza', models.PositiveIntegerField(max_length=3)),
                ('index_Onix', models.PositiveIntegerField(max_length=3)),
                ('index_Tracker', models.PositiveIntegerField(max_length=3)),
                ('index_Matiz', models.PositiveIntegerField(max_length=3)),
            ],
        ),
    ]
