# Generated by Django 4.0.1 on 2024-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='index_Cobalt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Equinox',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Gentra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Labo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Lacetti',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Malibu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Malibu2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Matiz',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Monza',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Nexia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Onix',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Spark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_Tracker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
